manager/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

app_name = 'manager'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<id>\d+)/modify/$', views.modify, name='modify'),
    url(r'^(?P<id>\d+)/del_confirm/$', views.del_confirm, name='del_confirm'),
    url(r'^(?P<id>\d+)/delete/$', views.delete, name='delete'),
    #url(r'^(?P<id>\d+)/mod_confirm/$', views.mod_confirm, name='mod_confirm'),
]

script_manager/urls.py
# -*- coding: utf-8 -*-
"""script_manager URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^manager/', include('manager.urls')),
    url(r'^$', RedirectView.as_view(url='/manager', permanent=True)),
    #url(r'^rest-api/',include('rest_framework.urls')),
    #url(r'^rest-swagger/', include('rest_framework_swagger.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Document(models.Model):
    author = models.CharField(max_length=30)
    tcid = models.CharField(max_length=30)
    docfile = models.FileField(upload_to='documents/%Y/%m/%d')
    detail = models.TextField()
    now = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.docfile

manager/forms.py
# -*- coding: utf-8 -*-
from django import forms

class ScriptlistForm(forms.Form):
    author = forms.CharField(max_length=30)
    tcid = forms.CharField(max_length=30)
    docfile = forms.FileField(label='Select Input simulator script file(.py)')
    detail = forms.CharField(widget=forms.Textarea)

manager/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Document
from .forms import ScriptlistForm

# -------------------------------------------------------------
def index(request):
    template_name = 'manager/index.html'

    if request.method == 'POST':
        forms = ScriptlistForm(request.POST, request.FILES)
        if forms.is_valid():
            newpost = Document(
                author=forms.cleaned_data['author'],
                tcid=forms.cleaned_data['tcid'],
                detail=forms.cleaned_data['detail'],
                docfile=request.FILES['docfile'],
            )
            newpost.save()
            return HttpResponseRedirect(reverse('manager:index'))
    else:
        forms = ScriptlistForm()
    scripts = Document.objects.order_by('-now')#[0:5]
    totalCnt = Document.objects.all().count()

    return render(request, template_name, {
                                        'scripts':scripts,
                                        'forms':forms,
                                        'totalCnt':totalCnt
    })

# -------------------------------------------------------------

def detail(request, id):
    template_name = 'manager/view.html'

    form = ScriptlistForm()

    scripts = Document.objects.get(id=id)
    return render(request, template_name, {
                                        'scripts':scripts,
                                        'form':form
    })

# -------------------------------------------------------------

def delete(request, id):

    posts = Document.objects.get(id=id)

    return render(request, 'manager/del.html', {'posts':posts} )

# -------------------------------------------------------------

def del_confirm(request, id):
    try:
        scripts = Document.objects.get(id=id)
        scripts.delete()
    except:
        raise Http404('Do not delete!')
    return HttpResponseRedirect(reverse('manager:index'))

# -------------------------------------------------------------

def modify(request, id):

    posts = Document.objects.get(id=id)

    print (request)
    if request.method == 'POST':
        form = ScriptlistForm(request.POST, request.FILES)

        if form.is_valid():
            modpost = posts(
                author=form.cleaned_data['author'],
                tcid=form.cleaned_data['tcid'],
                detail=form.cleaned_data['detail'],
                docfile=request.FILES['docfile']
            )
            modpost.save()
            return HttpResponseRedirect('/manager/detail/')

    else:

        form = ScriptlistForm(
            initial={
                'author':posts.author,
                'tcid':posts.tcid,
                'docfile':posts.docfile,
                'detail':posts.detail,
                'now':posts.now}
        )
    return render(request, 'manager/modify.html', {'form':form, 'posts':posts})

manager/templates/layout.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="euc-kr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=euc-kr" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <link rel ="shortcut icon" type = "image/x-icon" href="{% static 'manager/img/favicon.gif' %}" />

    <script>
    function goBack() {
        window.history.back();
    }
    </script>
</head>
<meta http-equiv="Content-Language" content="ko">
<body>
{% block content %}{% endblock %}
</body>
</html>

manager/templates/manager/confirm.html
{% extends "layout.html" %}
{% block title %}
Delete Confirm
{% endblock %}

{% block content %}

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'manager:index' %}">list로 이동</a>
    </div>
</nav>
<div class="container">
    <table class="table table-striped table-hover">
        <thead>
           <tr>
                <td><h3>분류</h3></td>
                <td><h3>내용</h3></td>
           </tr>
        </thead>

        <tbody>
          <tr><td width="250">작성자</td>      <td>{{ scripts.author }}</td></tr>
          <tr><td width="250">날짜</td>        <td>{{ scripts.author }}</td></tr>
          <tr><td width="250">TC ID</td>       <td>{{ scripts.author }}</td></tr>
          <tr><td width="250">Script File</td> <td>{{ scripts.author }}</td></tr>
          <tr><td width="250">설명</td>        <td>{{ scripts.author }}</td></tr>
        </tbody>

        <tfoot>
            <form action="/manager/detailview/{{scripts.id}}/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
                <tr>
                    <td>
                        <button type="button">삭제</button>
                    </td>
                    <td align="right">
                        </br>
                        해당 게시물을 삭제하시겠습니까?
                        <input type="submit" value="확인"/>
                    </td>
                </tr>
            </form>
        </tfoot>
    </table>
</div>

{% endblock %}

manager/templates/manager/del.html
{% extends "layout.html" %}
{% block title %}
Detail view Page
{% endblock %}

{% block content %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'manager:index' %}">list</a>
    </div>
</nav>
<div class="container">
    <table class="table table-striped table-hover">
        <thead>
           <tr>
                <td><h3>분류</h3></td>
                <td><h3>내용</h3></td>
           </tr>
        </thead>

        <tbody>
          <tr><td width="250">작성자</td>      <td>{{ posts.author }}</td></tr>
          <tr><td width="250">날짜</td>        <td>{{ posts.now|date:"y/m/d H:i:s" }}</td></tr>
          <tr><td width="250">TC ID</td>       <td>{{ posts.tcid }}</td></tr>
          <tr><td width="250">Script File</td> <td>{{ posts.docfile }}</td></tr>
          <tr><td width="250">설명</td>        <td>{{ posts.detail }}</td></tr>

        </tbody>

        <tfoot>

            {% csrf_token %}
                <tr>
                    <td>

                    </td>
                    <td align="right">
                        <p class="lead">해당 게시물을 삭제하시겠습니까?</p>
                        <a href="{% url 'manager:del_confirm' posts.id %}" class="btn btn-danger" role="button">Delete</a>
                        <button class="btn btn-default" onclick="goBack()">취소</button>

                    </td>
                </tr>

        </tfoot>
    </table>
</div>
{% endblock %}

manager/templates/manager/index.html
{% extends "layout.html" %}
{% block title %}
Script manager
{% endblock %}

{% block content %}
<div class="container">
    <center><h1>Script Manager</h1></center>
    Total : {{totalCnt}}
    <table class="table table-striped table-hover">
        <thead>
            <form action="{% url 'manager:index' %}" method="post" enctype="multipart/form-data">
                <tr>
                    <td><B>작성자:{{ forms.author }}</B></td>
                    <td><B>TC ID:{{ forms.tcid }}</B></td>
                    <td><B>Script 첨부:{{ forms.docfile }}</B></td>
                    <td><B>{{ forms.detail }}</B></td>
                    <td><input type="submit" class="btn btn-default" value="save"/></td>
                    {% csrf_token %}
                </tr>
            </form>
            <tr>
                <td><B>작성자</B></td>
                <td><B>TC ID</B></td>
                <td><B>Script File</B></td>
                <td><B>설명</B></td>
                <td><B>날짜</B></td>
            </tr>
        </thead>
        <tbody>
          {% for script in scripts %}
            <tr>
                <td>{{ script.author }}</td>
                <td> <a href="{% url 'manager:detail' script.id %}"> {{ script.tcid }} </a> </td>
                <td> <a href="{{ script.docfile.url }}"> {{ script.docfile.name }} </a> </td>
                <td> {{ script.detail }}</td>
                <td>{{ script.now|date:"y/m/d H:i:s" }}</td>
            {% endfor %}
        </tbody>
    </table>

</div>
{% endblock %}

manager/templates/manager/modify.html
{% extends "layout.html" %}
{% block title %}
Detail view Page
{% endblock %}

{% block content %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'manager:index' %}">list</a>
    </div>
</nav>
<div class="container">
    <table class="table table-striped table-hover">
        <thead>
           <tr>
                <td><h3>분류</h3></td>
                <td><h3>내용</h3></td>
           </tr>
        </thead>
         <form action="/manager/{{posts.id}}/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <tbody>
          <tr><td width="250">작성자</td>      <td>{{ form.author}}</td></tr>
          <tr><td width="250">날짜</td>        <td>{{ posts.now|date:"y/m/d H:i:s" }}</td></tr>
          <tr><td width="250">TC ID</td>       <td>{{ form.tcid }}</td></tr>
          <tr><td width="250">Script File</td> <td>{{ form.docfile }}</td></tr>
          <tr><td width="250">설명</td>        <td>{{ form.detail }}</td></tr>
        </tbody>

        <tfoot>

                <tr>
                    <td>
                        <a href="{% url 'manager:delete' posts.id %}" class="btn btn-danger" role="button">Delete</a>
                    </td>
                    <td align="right">
                        <input type="submit" class="btn btn-primary" value="save"/>
                        <button class="btn btn-default" onclick="goBack()">취소</button>
                    </td>
                </tr>
        </tfoot>
            </form>
    </table>
</div>
{% endblock %}

manager/templates/manager/view.html
{% extends "layout.html" %}
{% block title %}
Detail view Page
{% endblock %}

{% block content %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'manager:index' %}">list</a>
    </div>
</nav>
<div class="container">
    <table class="table table-striped table-hover">
        <thead>
           <tr>
                <td><h3>분류</h3></td>
                <td><h3>내용</h3></td>
           </tr>
        </thead>

        <tbody>
          <tr><td width="250">작성자</td>      <td>{{ scripts.author }}</td></tr>
          <tr><td width="250">날짜</td>        <td>{{ scripts.now|date:"y/m/d H:i:s" }}</td></tr>
          <tr><td width="250">TC ID</td>       <td>{{ scripts.tcid }}</td></tr>
          <tr><td width="250">Script File</td> <td><a href="{{ scripts.docfile.url }}"> {{scripts.docfile }}</a></td></tr>
          <tr><td width="250">설명</td>        <td>{{ scripts.detail }}</td></tr>
        </tbody>

        <tfoot>
            <form action="/manager/{{scripts.id}}/modify/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
                <tr>
                    <td>
                        <a href="{% url 'manager:modify' scripts.id %}" class="btn btn-warning" role="button">Modify</a>
                        <a href="{% url 'manager:delete' scripts.id %}" class="btn btn-danger" role="button">Delete</a>
                    </td>
                    <td align="right">
                        <a href="{% url 'manager:index' %}" class="btn btn-default">list</a>
                    </td>
                </tr>
            </form>
        </tfoot>
    </table>
</div>
{% endblock %}